### PR TITLE
Organize SlicerSALT module list

### PR DESCRIPTION
**Pull request by vicory**
- [x]  (1) Rename and re-categorize SlicerSALT modules to improve organization. This part was integrated in https://github.com/Kitware/SlicerSALT/commit/5e8e3ba7a4159144ce6f950d2f8dec7bfbfaed96
- [ ] (2) Hide unused Slicer modules to clean up interface

for reference, the changes associated with (1) are the following:

```
MFSDA

* MFSDA module
  - title   :   MSFDA -> Covariate Significance Testing
  - category: Pvalues -> Shape Analysis

* MFSDA_createShapes module
  - category: PValues -> Shape Analysis.Advanced

* MFSDA_run module
  - category: PValues -> Shape Analysis.Advanced

ShapeVariationAnalyzer

* ShapeVariationAnalyzer module
  - title   : ShapeVariationAnalyzer -> Population Analysis
  - category:          Decomposition -> Shape Analysis

* shapepca module
  - category:          Decomposition -> Shape Analysis.Advanced

* shapepcalib module
  - category:          Decomposition -> Shape Analysis.Advanced

shape4D

* shape4D module
  - category: Shape Analysis -> Shape Analysis.Advanced

ShapePopulationViewer

* Extension metadata
  - EXTENSION_CATEGORY: Shape Analysis -> Shape Visualization

* ShapePopulationViewer module
  - title   :    ShapePopulationViewer -> Shape Population Viewer
  - category:           Quantification -> Shape Visualization

ShapeRegressionExtension

* RegressionComputation module
  - title   :   RegressionComputation -> Regression Computation
  - category:        Shape Regression -> Shape Analysis

* RegressionVisualization module
  - title   : RegressionVisualization -> Regression Visualization
  - category:        Shape Regression -> Shape Analysis

SPHARM-PDM

* GenParaMeshCLP module
  - category:                SPHARM -> Shape Creation.Advanced

* ParaToSPHARMMeshCLP module
  - category:                SPHARM -> Shape Creation.Advanced

* SegPostProcessCLP module
  - category:                SPHARM -> Shape Creation.Advanced

* ShapeAnalysisModule module
  - title   : Shape Analysis Module -> SPHARM-PDM Generator
  - category:                SPHARM -> Shape Creation
```

### CODE REVIEW

**Comment by jcfr** [comment]
> Hide unused Slicer modules to clean up interface

I will follow up on this.

**Comment by jcfr** [comment]
For reference, the following code allow to hide the module selected below:

```python
moduleMenu = slicer.util.mainWindow().moduleSelector().modulesMenu()
moduleMenu.removeCategory("Diffusion")
moduleMenu.removeCategory("Converters")
moduleMenu.removeCategory("Legacy")
moduleMenu.removeCategory("Registration.Specialized")

removeFromAllModules = False
moduleMenu.removeModule("Reformat", removeFromAllModules)

removeFromAllModules = True
moduleMenu.removeModule("Editor", removeFromAllModules)
```

-------------------------------------

* [ ] All Modules
  * [ ] Annotations
  * [ ] Cameras
  * [ ] Colors
  * [ ] Covariate Significance Testing
  * [ ] Crop Volume
  * [ ] Crop volume sequence
  * [ ] Data
  * [ ] Data Importer
  * [ ] DICOM
  * [ ] DICOM Patcher
  * [ ] DICOM Scalar Volume Plugin
  * [x] Editor
  * [ ] Event Broker
  * [ ] Extension Wizard
  * [ ] GenParaMesh
  * [ ] Group Wise Registeration Module
  * [ ] Group-wise Registration for Shape Correspondence (Groups)
  * [ ] Home
  * [ ] Markups
  * [ ] Merge Models
  * [ ] Mesh To Label Map
  * [ ] MFSDA_createShapes
  * [ ] MFSDA_run
  * [ ] Model Maker
  * [ ] Model To Model Distance
  * [ ] Models
  * [ ] ParaToSPHARMMesh
  * [ ] Plots
  * [ ] Population Analysis
  * [ ] Reformat
  * [ ] Regression Computation
  * [ ] Regression Visualization
  * [ ] Resample DTI Volume
  * [ ] Resample Scalar/Vector/DWI Volume
  * [ ] RigidAlignment
  * [ ] Screen Capture
  * [ ] Segment Editor
  * [ ] Segment Statistics
  * [ ] Segmentations
  * [ ] SegPostProcess
  * [ ] Sequence browser
  * [ ] Sequences
  * [ ] Shape PCA analysis
  * [ ] shape4D
  * [ ] shapepcalib
  * [ ] ShapePopulationViewer
  * [ ] Skeletal Representation Initializer
  * [ ] Skeletal Representation Visualizer
  * [ ] SPHARM-PDM Correspondence Improvement
  * [ ] SPHARM-PDM Generator
  * [ ] Surface Remeshing Tool
  * [ ] Surface Toolbox
  * [ ] Tables
  * [ ] Terminologies
  * [ ] Transforms
  * [ ] Volume Rendering
  * [ ] Volumes
* [ ] Home
* [ ] Annotations
* [ ] Data
* [ ] DICOM
* [ ] Markups
* [ ] Models
* [ ] Segment Editor
* [ ] Segmentations
* [ ] Transforms
* [ ] Volume Rendering
* [ ] Volumes
* [ ] Informatics
  * [ ] Annotations
  * [ ] Colors
  * [ ] Data
  * [ ] DICOM
  * [ ] Markups
  * [ ] Plots
  * [ ] Tables
  * [ ] Terminologies
* [ ] Registration
  * [ ] Transforms
  * [x] Specialized
    * [x] Reformat
* [ ] Segmentation
  * [ ] Segment Editor
* [ ] Quantification
  * [ ] Model To Model Distance
  * [ ] Segment Statistics
* [x] Diffusion
  * [x] Utilities
    * [x] Resample DTI Volume
    * [x] Resample Scalar/Vector/DWI Volume
* [ ] Surface Models
  * [ ] Merge Models
  * [ ] Mesh To Label Map
  * [ ] Model Maker
  * [ ] Surface Toolbox
* [x] Converters
  * [x] Crop Volume
* [ ] Utilities
  * [ ] DICOM Patcher
  * [ ] Screen Capture
* [ ] Developer Tools
  * [ ] Cameras
  * [ ] Event Broker
  * [ ] Extension Wizard
  * [ ] DICOM Plugins
    * [ ] DICOM Scalar Volume Plugin
* [x] Legacy
  * [x] Editor
* [ ] Sequences
  * [ ] Crop volume sequence
  * [ ] Sequence browser
  * [ ] Sequences
* [ ] Shape Analysis
  * [ ] Covariate Significance Testing
  * [ ] Population Analysis
  * [ ] Regression Computation
  * [ ] Regression Visualization
  * [ ] ShapePopulationViewer
  * [ ] Advanced
    * [ ] MFSDA_createShapes
    * [ ] MFSDA_run
    * [ ] Shape PCA analysis
    * [ ] shape4D
    * [ ] shapepcalib
* [ ] Shape Analysis Toolbox
  * [ ] Data Importer
  * [ ] Home
* [ ] Shape Creation
  * [ ] SPHARM-PDM Correspondence Improvement
  * [ ] SPHARM-PDM Generator
  * [ ] Advanced
    * [ ] GenParaMesh
    * [ ] ParaToSPHARMMesh
    * [ ] RigidAlignment
    * [ ] SegPostProcess
* [ ] Groups
  * [ ] Group Wise Registeration Module
  * [ ] Group-wise Registration for Shape Correspondence (Groups)
* [ ] Skeleton, topology
  * [ ] Skeletal Representation Initializer
  * [ ] Skeletal Representation Visualizer
* [ ] Unspecified
  * [ ] Surface Remeshing Tool

**Comment by jcfr** [comment]
The list of modules was generated using snipped like the following:

```python
def displayMenu(parentMenu, indent):
  if parentMenu is None:
    return
  for action in parentMenu.actions():
    if action.text:
      print("%s* [ ] %s" % (indent, action.text))
    displayMenu(action.menu(), indent + "  ")


moduleMenu = mainWindow().moduleSelector().modulesMenu()
displayMenu(moduleMenu, "")
```

**Comment by jcfr** [comment]
@bpaniagua  

* Which categories/modules should we hide ? 
* From both "All Modules" and top-level categories ? 

I also think we could simply skip building some other modules:
* [x] Editor



Please, select below:

* [ ] All Modules
  * [ ] Annotations
  * [ ] Cameras
  * [ ] Colors
  * [ ] Covariate Significance Testing
  * [ ] Crop Volume
  * [ ] Crop volume sequence
  * [ ] Data
  * [ ] Data Importer
  * [ ] DICOM
  * [ ] DICOM Patcher
  * [ ] DICOM Scalar Volume Plugin
  * [ ] Editor
  * [ ] Event Broker
  * [ ] Extension Wizard
  * [ ] GenParaMesh
  * [ ] Group Wise Registeration Module
  * [ ] Group-wise Registration for Shape Correspondence (Groups)
  * [ ] Home
  * [ ] Markups
  * [ ] Merge Models
  * [ ] Mesh To Label Map
  * [ ] MFSDA_createShapes
  * [ ] MFSDA_run
  * [ ] Model Maker
  * [ ] Model To Model Distance
  * [ ] Models
  * [ ] ParaToSPHARMMesh
  * [ ] Plots
  * [ ] Population Analysis
  * [ ] Reformat
  * [ ] Regression Computation
  * [ ] Regression Visualization
  * [ ] Resample DTI Volume
  * [ ] Resample Scalar/Vector/DWI Volume
  * [ ] RigidAlignment
  * [ ] Screen Capture
  * [ ] Segment Editor
  * [ ] Segment Statistics
  * [ ] Segmentations
  * [ ] SegPostProcess
  * [ ] Sequence browser
  * [ ] Sequences
  * [ ] Shape PCA analysis
  * [ ] shape4D
  * [ ] shapepcalib
  * [ ] ShapePopulationViewer
  * [ ] Skeletal Representation Initializer
  * [ ] Skeletal Representation Visualizer
  * [ ] SPHARM-PDM Correspondence Improvement
  * [ ] SPHARM-PDM Generator
  * [ ] Surface Remeshing Tool
  * [ ] Surface Toolbox
  * [ ] Tables
  * [ ] Terminologies
  * [ ] Transforms
  * [ ] Volume Rendering
  * [ ] Volumes
* [ ] Home
* [ ] Annotations
* [ ] Data
* [ ] DICOM
* [ ] Markups
* [ ] Models
* [ ] Segment Editor
* [ ] Segmentations
* [ ] Transforms
* [ ] Volume Rendering
* [ ] Volumes
* [ ] Informatics
  * [ ] Annotations
  * [ ] Colors
  * [ ] Data
  * [ ] DICOM
  * [ ] Markups
  * [ ] Plots
  * [ ] Tables
  * [ ] Terminologies
* [ ] Registration
  * [ ] Transforms
  * [ ] Specialized
    * [ ] Reformat
* [ ] Segmentation
  * [ ] Segment Editor
* [ ] Quantification
  * [ ] Model To Model Distance
  * [ ] Segment Statistics
* [ ] Diffusion
  * [ ] Utilities
    * [ ] Resample DTI Volume
    * [ ] Resample Scalar/Vector/DWI Volume
* [ ] Surface Models
  * [ ] Merge Models
  * [ ] Mesh To Label Map
  * [ ] Model Maker
  * [ ] Surface Toolbox
* [ ] Converters
  * [ ] Crop Volume
* [ ] Utilities
  * [ ] DICOM Patcher
  * [ ] Screen Capture
* [ ] Developer Tools
  * [ ] Cameras
  * [ ] Event Broker
  * [ ] Extension Wizard
  * [ ] DICOM Plugins
    * [ ] DICOM Scalar Volume Plugin
* [ ] Legacy
  * [ ] Editor
* [ ] Sequences
  * [ ] Crop volume sequence
  * [ ] Sequence browser
  * [ ] Sequences
* [ ] Shape Analysis
  * [ ] Covariate Significance Testing
  * [ ] Population Analysis
  * [ ] Regression Computation
  * [ ] Regression Visualization
  * [ ] ShapePopulationViewer
  * [ ] Advanced
    * [ ] MFSDA_createShapes
    * [ ] MFSDA_run
    * [ ] Shape PCA analysis
    * [ ] shape4D
    * [ ] shapepcalib
* [ ] Shape Analysis Toolbox
  * [ ] Data Importer
  * [ ] Home
* [ ] Shape Creation
  * [ ] SPHARM-PDM Correspondence Improvement
  * [ ] SPHARM-PDM Generator
  * [ ] Advanced
    * [ ] GenParaMesh
    * [ ] ParaToSPHARMMesh
    * [ ] RigidAlignment
    * [ ] SegPostProcess
* [ ] Groups
  * [ ] Group Wise Registeration Module
  * [ ] Group-wise Registration for Shape Correspondence (Groups)
* [ ] Skeleton, topology
  * [ ] Skeletal Representation Initializer
  * [ ] Skeletal Representation Visualizer
* [ ] Unspecified
  * [ ] Surface Remeshing Tool

**Comment by bpaniagua** [comment]
Hi @jcfr and @vicory 
I have marked the modules that should be hidden in the last post from JC.
Some additional notes: we should keep the "All modules" menu hidden. It is quite overwhelming to see everything that is available in Slicer (or SliceSALT in this case).

My only inner debate is whether or not to leave the segment editor visible. It might be a good thing to have there if the user wants to quickly patch a segmentation (might be also something interesting to have accesible through the data importer?), but definitely add a level of complication that we tried to have out of SALT. When designing the project, I purposely decided to not have any segmentation functionality in SALT. 

I propose to hide it only, still leave it in there, show it if we get a request. Thoughts?

**Comment by vicory** [comment]
Did a quick glance through the built modules on the latest version and it seems to match the selections made above. It is still a little hard to pick the SALT-specific modules out from the list so I'm curious about a couple of things:

1. Is it possible to sort the modules in something other than alphabetical order so that the SALT modules appear first?
2. Is it possible to have some modules in a different sub-area of the menu. I know for instance if you import a locally built module into Slicer it will show up separated out from the built-in module list

Just trying to think of ways to make it easier to jump straight to the SALT modules.

**Comment by jcfr** [comment]
Thanks for the update.

Now I am done [fixing](https://discourse.slicer.org/t/maintenance-of-slicer-kitware-com-planned-on-thursday-april-18th-from-2-to-3pm-edt/6533/6?u=jcfr) the Slicer extension server, I will be able to finalize this.

> Is it possible to sort the modules in something other than alphabetical order so that the SALT modules appear first?

We should be able to have SlicerSALT module appear in category after the favorite module, and before the default categories.

> Is it possible to have some modules in a different sub-area of the menu. I know for instance if you import a locally built module into Slicer it will show up separated out from the built-in module list

Yes. 

I will follow up shortly with an update.

**Comment by jcfr** [comment]
After I integrate this new set of changes, here is what we would have:

image

It will be possible to:
* tweak the order of categories as needed
* have module listed in the top-level category along side the Home module (this can be done by setting module category to `["", "Category"]`
* remove unwanted modules from the top-level category (e.g we could remove Annotations, Volume Rendering, ... )

**Pull request merged**
