### PR TITLE
COMP: Update SlicerSRep2 extension

### PR DESCRIPTION
**Pull request by Connor-Bowley**
Fixes build issues on Windows

### CODE REVIEW

**Comment by Connor-Bowley** [comment]
Note: the SlicerSRep2 repo and extension will soon be merged into the original SlicerSkeletalRepresentation extension, but I would like to get a clean build of SlicerSALT on CDash before then (at least where SReps are concerned).

**Comment by allemangD** [comment]
The build still succeeds on my Ubuntu 20 machine, but given the purpose of the PR I'm not sure how useful that is. I've been trying to build on my Windows machine but have issues with Fortran and Visual Studio not cooperating and haven't been able to build yet. There are no GTest errors so far.

There is a warning that the type specifier `:BOOL` is missing from this line:

https://github.com/KitwareMedical/SlicerSRep2/commit/65be4f476c732295905a7841a7dbbdfc21595be7#diff-e85a0eb5f50cb53144a79fcfebef5f97d14e0295860b7758c69ef177eaac8634R62

**Comment by allemangD** [comment]
It would be nice to update `FindVcvars.cmake` in SALT and its dependencies so it can be built with newer versions of Visual Studio.

The latest tag is `v1.6` with file hash `0fd1104a5e0f91f89b64dd700ce57ab9f7d7356fcabe9c895e62aca32386008e`.

https://github.com/Kitware/SlicerSALT/blob/07d493b1a64fe1a00e107b029d3a73aaf7ac18b0/CMake/CMakeLists.txt#L3-L4

https://github.com/slicersalt/Slicer/blob/slicersalt-2020-07-09-a9f89f4e9d/CMake/FindVcvars.cmake

https://github.com/slicersalt/SPHARM-PDM/blob/slicersalt-2021-10-29-cdc40bd/CMake/CMakeLists.txt#L3-L4

https://github.com/slicersalt/GROUPS/blob/slicersalt-2021-05-26-b2bd6008/CMake/CMakeLists.txt#L3-L4

https://github.com/commontk/AppLauncher/blob/master/msvc-static-configure.cmake#L41-L42

**Comment by allemangD** [comment]
The Windows build of d0fa3a8 completed without issues, and an Ubuntu build of 699c614 completed without issues. LGTM; I'll go ahead and merge.

**Review by allemangD — APPROVED** [review]
LGTM

**Pull request merged**
