### PR TITLE
ENH: Update SVA tag

### PR DESCRIPTION
**Pull request by bpaniagua**
Update SVA to include @lbumbolo additions to the module

### CODE REVIEW

**Comment by bpaniagua** [comment]
See https://github.com/slicersalt/ShapeVariationAnalyzer/tree/slicersalt-2020-01-15-d8c9fc0
for associated changes

**Comment by jcfr** [comment]
Well done

Nitpick:

I suggest to update the commit message to something like this:

```
ENH: Update ShapeVariationAnalyzer to include export tab

List of changes:

$ git shortlog a8443fe033..d8c9fc00ad9 --no-merges 
Louis Bumbolo (1):
      ENH: Add Export tab
```

**Comment by bpaniagua** [comment]
@jcfr 
check it out!

**Comment by jcfr** [comment]
Almost, whenever possible I also suggest to have a more descriptive subject for the commit message. For example:

```
ENH: Update ShapeVariationAnalyzer to include export tab
```

**Comment by bpaniagua** [comment]
@jcfr missed that...
check it, check it now!

**Comment by bpaniagua** [comment]
You are assuming right.

**Comment by bpaniagua** [comment]
@vicory thanks!
@jcfr good to merge

**Pull request merged**
