### PR TITLE
Merge latest changes from DataImporter

### PR DESCRIPTION
**Pull request by bpaniagua**
Refs #158 
Review @jcfr @vicory

### CODE REVIEW

**Comment by jcfr** [comment]
I suggest the following integration approaches:

```
git checkout -b dataimporter-update
git remote add lopezmt git://github.com/lopezmt/SlicerSALT
git fetch lopezmt
git cherry-pick bb90e36..f5c6193   # Resolve conflict
```

And then create a PR

**Comment by bpaniagua** [comment]
@jcfr will re-do PR according to this suggestion

**Comment by jcfr** [comment]
For the update of the PR, it may be easier to cherry-pick each commit one by one. That conflict resolution may  be easier ..

**Comment by jcfr** [comment]
Closing. This PR is superseded  by #160

**Pull request closed without merging**
