### PR TITLE
Update Slicer, fix ShapePopulationViewer crash and improve UX updating external projects

### PR DESCRIPTION
**Pull request by jcfr**
Key ShapePopulationViewer changes are the following:
* Add support for explicitly loading vtkMRMLModelNode from Slicer scene
* Automatically load model node added to the Slicer scene. This means
  drag and drop of models is supported.
* Support export to PDF, SVG, ... in Slicer
* Improve Slicer module widget layout

Some illustrations are posted in https://github.com/Kitware/SlicerSALT/pull/133#issuecomment-439527334

### CODE REVIEW

**Comment by jcfr** [comment]
@bpaniagua commit "COMP: Prevent finding of wrong Qt version" should prevent finding for wrong Qt version. It should address the startup crash we experienced on your linux workstation the other day

**Comment by bpaniagua** [comment]
Thanks @jcfr I am reviewing and testing before integrating.
Will let you know!

**Comment by vicory** [comment]
The RigidAlignment module is throwing the following error when trying to invoke SPV:

> Could not find logic for module 'ShapePopulationViewer'

What is the correct way to run/switch to this new version from python?

**Comment by jcfr** [comment]
Thanks for testing. I will follow up later tonight.

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/Kitware/SlicerSALT/pull/135

**Pull request closed without merging**
