### PR TITLE
ENH: Update to Slicer 4.11-2018-11-08-94fb4a634

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by vicory** [comment]
Currently getting an error building against this version of Slicer:

Error copying file (if different) from "/work/SALT/build/RigidAlignment/RigidAlignment.xml" to "/./RigidAlignment.xml".

Looks like the LOCAL_SEM_RUNTIME_OUTPUT_DIRECTORY isn't being set properly?

**Comment by jcfr** [comment]
I will report back on my local build complete

**Comment by bpaniagua** [comment]
I also have a local build going

**Comment by bpaniagua** [comment]
My local build seems to be crashing while linking SRemesh, this is part of Groups.

[ 66%] Built target SRemeshLib
[ 83%] Linking CXX executable SRemesh
Copying XML file 'SRemesh.xml' along side the executable
Error copying file (if different) from "/work/Projects/slicerSALT/development/jcfr/SlicerSALT-build/SurfRemesh/SRemesh.xml" to "/./SRemesh.xml".
CMakeFiles/SRemesh.dir/build.make:85: recipe for target 'SRemesh' failed
make[5]: *** [SRemesh] Error 1
make[5]: *** Deleting file 'SRemesh'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/SRemesh.dir/all' failed
make[4]: *** [CMakeFiles/SRemesh.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
slicersources-build/CMakeFiles/SurfRemesh.dir/build.make:112: recipe for target 'slicersources-build/SurfRemesh-prefix/src/SurfRemesh-stamp/SurfRemesh-build' failed
make[2]: *** [slicersources-build/SurfRemesh-prefix/src/SurfRemesh-stamp/SurfRemesh-build] Error 2
CMakeFiles/Makefile2:387: recipe for target 'slicersources-build/CMakeFiles/SurfRemesh.dir/all' failed
make[1]: *** [slicersources-build/CMakeFiles/SurfRemesh.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jcfr** [comment]
I was also able to reproduce, I will follow up with an update.

**Comment by jcfr** [comment]
For some reason `SlicerExecutionModel_DEFAULT_CLI_RUNTIME_OUTPUT_DIRECTORY` is set to an empty path and the CLI CMakeCache.txt

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/Kitware/SlicerSALT/pull/132 fixing CLI build issues.

> My local build seems to be crashing while linking SRemesh, this is part of Groups.

For future reference, the problem was during copy of the XML file and not linking of the module. It is fixed by [r27543](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27543)

```
Copying XML file 'SRemesh.xml' along side the executable
Error copying file (if different) from "/work/Projects/slicerSALT/development/jcfr/SlicerSALT-build/SurfRemesh/SRemesh.xml" to "/./SRemesh.xml".
```

**Pull request closed without merging**
