### PR TITLE
WIP:  SlicerSALT 2.2 release - do not merge until all other 2.2 PRs are done

### PR DESCRIPTION
**Pull request by sjh26**

### CODE REVIEW

**Comment by sjh26** [comment]
Will do!

**Comment by bpaniagua** [comment]
@sjh26 Packages are ready to be generated!
Please, go ahead.

**Comment by jcfr** [comment]
:tada:

**Comment by bpaniagua** [comment]
Fiesta!

**Comment by vicory** [comment]
Siesta?

**Comment by jcfr** [comment]
Siesta -> Fiesta -> Siesta -> ...

**Pull request merged**
