### PR TITLE
ENH: Update Slicer

### PR DESCRIPTION
**Pull request by jcfr**
* Add python3 support
* Improved markup and annotation module
* Improved DICOM module
* Improved user interaction
* Update ITK version to ITKv5 rc01
* Add forward reference support to CLIs

### CODE REVIEW

**Comment by vicory** [comment]
Getting this error building on Linux:

`CMake Error at /work/SALT/build_python3/CTKAPPLAUNCHER/CMake/ctkAppLauncher.cmake:278 (message):
  DESTINATION_DIR [/work/SALT/build_python3/Slicer-build/bin] doesn't seem to
  exist !
`

**Comment by jcfr** [comment]
I will shortly publish a round of updates addressing remaining issues.

**Comment by jcfr** [comment]
This PR is now expected to:
* build cleanly 
* allow to start SlicerSALT without any runtime error related to python3

@vicory Make sure you do a clean build.

**Comment by jcfr** [comment]
I will now work on enabling MSFDA and addressing associated issues. This should allow us to move forward with #97

**Comment by jcfr** [comment]
Within the MFSDA project, it looks like there are three Slicer modules:
* loadable module MSFDA
* CLI `MFSDA_createShapes`
* CLI `MSFDA_run`

The MSFDA loadable failed to load because it tries to import functions from `MSFDA_run` and `MFSDA_createShapes`, this used to work when the file had the `.py` extension but is now broken.

Is the MSFDA module expected to work ? If yes, it shouldn't be too difficult to fix. I just want to have a clear idea of the different use cases we want to support.

**Pull request merged**
