### PR TITLE
Update spv spharmpdm modeltomodeldistance

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by vicory** [comment]
It seems like the specified ModelToModelDistance commit doesn't exist on https://github.com/slicersalt/3DMetricTools. We should either point to the NIRALUser repo or update our fork.

**Comment by jcfr** [comment]
> or update our fork

Thanks for the report. Should be fix now.

**Comment by vicory** [comment]
On Windows I'm now getting an inconsistent dll linkage error from ShapePopulationViewer:

```
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(98): warning C4273: 'qSlicerShapePopulationViewerModuleWidget::qt_static_metacall': inconsistent dll linkage
z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/qSlicerShapePopulationViewerModuleWidget.h(39): note: see previous definition of 'qt_static_metacall'
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(116): warning C4273: 'staticMetaObject': inconsistent dll linkage
z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/qSlicerShapePopulationViewerModuleWidget.h(39): note: see previous definition of 'public: static QMetaObject const qSlicerShapePopulationViewerModuleWidget::staticMetaObject'
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(116): error C2491: 'qSlicerShapePopulationViewerModuleWidget::staticMetaObject': definition of dllimport static data member not allowed
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(123): warning C4273: 'qSlicerShapePopulationViewerModuleWidget::metaObject': inconsistent dll linkage
z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/qSlicerShapePopulationViewerModuleWidget.h(39): note: see previous definition of 'metaObject'
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(128): warning C4273: 'qSlicerShapePopulationViewerModuleWidget::qt_metacast': inconsistent dll linkage
z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/qSlicerShapePopulationViewerModuleWidget.h(39): note: see previous definition of 'qt_metacast'
E\ShapePopulationViewer\src\moc_qSlicerShapePopulationViewerModuleWidget.cpp(136): warning C4273: 'qSlicerShapePopulationViewerModuleWidget::qt_metacall': inconsistent dll linkage
z:\ss\b4\slicer-build\e\shapepopulationviewer\src\../../../../ShapePopulationViewer/src/qSlicerShapePopulationViewerModuleWidget.h(39): note: see previous definition of 'qt_metacall'
ninja: build stopped: subcommand failed.
FAILED: slicersources-build/Slicer-prefix/src/Slicer-stamp/Slicer-build
cmd.exe /C "cd /D Z:\SS\b4\Slicer-build && "C:\Program Files\CMake\bin\cmake.exe" --build . && "C:\Program Files\CMake\bin\cmake.exe" -E touch Z:/SS/b4/slicersources-build/Slicer-prefix/src/Slicer-stamp/Slicer-build"
ninja: build stopped: subcommand failed.
```

Bisect puts the blame on commit https://github.com/slicersalt/ShapePopulationViewer/commit/53edc736d1994990615d049372f8d2a9f916cf78:

```
$ git bisect log
git bisect start
# bad: [af15572fcf4a55b81f0d2c65b837150615232c91] COMP: Pass _moc_options to QT5_WRAP_CPP
git bisect bad af15572fcf4a55b81f0d2c65b837150615232c91
# good: [bf7c815816cc7c77acb7b1bb6ae2dee1df92b047] COMP: Do not use function setTopWidgetsVisible
git bisect good bf7c815816cc7c77acb7b1bb6ae2dee1df92b047
# bad: [683f32508da514c8351c3bf71904ebeeeaac1b6e] ENH: Rename module for SALT
git bisect bad 683f32508da514c8351c3bf71904ebeeeaac1b6e
# bad: [4c4757ff5913e87de58e21f096ed51e509500440] Merge pull request #46 from jcfr/fix-configuration-updating-ITKSetStandardCompilerFlags
git bisect bad 4c4757ff5913e87de58e21f096ed51e509500440
# bad: [53edc736d1994990615d049372f8d2a9f916cf78] COMP: Fix configuration updating ITKSetStandardCompilerFlags
git bisect bad 53edc736d1994990615d049372f8d2a9f916cf78
# first bad commit: [53edc736d1994990615d049372f8d2a9f916cf78] COMP: Fix configuration updating ITKSetStandardCompilerFlags
```

**Comment by jcfr** [comment]
Look like the `-DqSlicerShapePopulationViewerModule_EXPORTS` flag is not specified when compiling the module

**Comment by jcfr** [comment]
Problem has been identified and fix is being integrate into ShapePopulationViewer

**Pull request merged**
