### PR TITLE
Update slicer and improve extension integration

### PR DESCRIPTION
**Pull request by jcfr**
Bundle SPHARM-PDM as a regular extension

Key ShapePopulationViewer changes are the following:
* Add support for explicitly loading vtkMRMLModelNode from Slicer scene
* Automatically load model node added to the Slicer scene. This means
  drag and drop of models is supported.
* Support export to PDF, SVG, ... in Slicer
* Improve Slicer module widget layout

Some illustrations are posted in https://github.com/Kitware/SlicerSALT/pull/133#issuecomment-439527334

### CODE REVIEW

**Comment by vicory** [comment]
Getting this error building on Linux:

> CPack: - Run preinstall target for: Slicer
CPack: - Install project: Slicer
CMake Error at /work/SALT/build_20181120/Slicer-build/E/SPHARM-PDM/CommandLineTool/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/work/SALT/build_20181120/slicersources-src/CommandLineTool/SPHARM-PDM-parameters.ini".
Call Stack (most recent call first):
  /work/SALT/build_20181120/Slicer-build/E/SPHARM-PDM/cmake_install.cmake:89 (include)
  /work/SALT/build_20181120/Slicer-build/cmake_install.cmake:59 (include)
CPack Error: Error when generating package: SlicerSALT

I'm assuming its a problem with using CMAKE_SOURCE_DIR variable [here](https://github.com/jcfr/SPHARM-PDM/blob/support-direct-integration-in-custom-slicer-app/CommandLineTool/CMakeLists.txt#L3) due to the new structure of the extension but have not tested that theory yet.

**Comment by jcfr** [comment]
> The RigidAlignment module is throwing the following error when trying to invoke SPV:

The following need to be updated:

https://github.com/jcfr/GROUPS/blob/4df02be2f877f94855372bbdf63db63eeb467285/Modules/Scripted/RigidAlignmentModule/RigidAlignmentModule.py#L178-L188

to call function from the shapepopulationviewer loadable module.

I will shortly push a commit exposing the function `loadCSVFile` and updating the `RigidAlignmentModule` module.

**Comment by jcfr** [comment]
> Getting SPHARM-PDM error building on Linux:

Thanks for testing, I will follow up later with an update

**Comment by jcfr** [comment]
> SPHARM-PDM packaging issue

Commit 2e85f6b fixes the SPHARM-PDM packaging issue

**Comment by bpaniagua** [comment]
@jcfr Thank you so much for all your work.
I tried in Linux and all works fine.

@vicory  could you please quickly test jc's branch on linux?

**Comment by jcfr** [comment]
:tada:

**Comment by bpaniagua** [comment]
hurray!

**Pull request merged**
