### PR TITLE
Update Slicer and adopt SlicerCustomAppTemplate v2

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@laurapascal @bpaniagua  This is ready for review and integration.

**Comment by vicory** [comment]
@jcfr Any more changes coming or is this ready for review?

**Comment by jcfr** [comment]
I suggest to move forward and integrate.

**Comment by jcfr** [comment]
Also after integrating this PR, #38 and #39 could be closed.

**Comment by vicory** [comment]
There are currently conflicts with ShapePopulationViewer and Qt5/VTK 9, I'm working on a fix.

**Comment by jcfr** [comment]
Indeed, if i recall ShapePopulationViewer should be updated to support
Qt5/VTK9

**Comment by vicory** [comment]
ShapePopulationViewer problems should be fixed, but I've discovered a new issue: the qMRML widgets are not showing up under qt.QUiLoader().availableWidgets(), causing scripted modules to not work properly.

**Comment by jcfr** [comment]
> the qMRML widgets are not showing up under qt.QUiLoader().availableWidgets()

Is this specific to a platform ? Or reproducible on Linux, macOS and Windows ?

**Comment by vicory** [comment]
I've only tested on Linux thus far.

**Comment by phcerdan** [comment]
I am going to test this, it should be a priority. If we do not have to maintain backwards compatibility... better to get up-to-date with slicer master and go for qt5.

**Comment by bpaniagua** [comment]
Thank you, Pablo. After you test it let us know how it goes.

**Comment by phcerdan** [comment]
One issue found, not sure if this is the expected behavior. If I want to pass settings to Slicer, I have to use SlicerSALT as a prefix, not Slicer.

`Slicer_USE_SYSTEM_python:BOOL=ON` is ignored, and Slicer will fetch and build python.
However `SlicerSALT_USE_SYSTEM_python:BOOL=ON` works.

This is because `${CMAKE_PROJECT_NAME}` is `SlicerSALT` in `Slicer/Superbuild.cmake` and all the scripts `External_xxx.cmake`

**Comment by bpaniagua** [comment]
Seems about right to me. @jcfr @vicory what do you think?

**Comment by jcfr** [comment]
@phcerdan Makes sense. 

From a usability stand point, it looks like we should always have the option starting with `Slicer_`. 

Would that help reduce  confusion ?

**Comment by jcfr** [comment]
> Slicer_USE_SYSTEM_python:BOOL=ON is ignored, and Slicer will fetch and build python

Following Slicer [r27286](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27286), option associated with Slicer core will all start with `Slicer_`

**Comment by phcerdan** [comment]
Awesome @jcfr, I agree that it will reduce confusion, thanks!

**Comment by jcfr** [comment]
Could you report here the content of `SlicerSALTLauncherSettings.ini` ? (it is available in the `Slicer-build` directory)

In a regular build directory, the VTK module is found here: `./VTKv9-build/lib/python2.7/site-packages/vtkmodules/vtkCommonKitPython.so`

In you case, I am assuming you built from a virtual environment ? can you locate that libraries ?

**Comment by phcerdan** [comment]
> I suspect that the launcher settings doesn't account for the path /home/phc/Software/Slicer/buildSystemQtPython-RelWithDebInfo/VTKv9-build/lib/python2.7/site-packages/vtkmodules/ 

Spot on, it shouldn't, it makes no sense for my SALT installation (in folder `Software/Shape/SALT/buildRelWithDebInfo`) to know anything about my independent Slicer installation (in folder `Software/Slicer/buildRelWithDebInfo`). I wonder how this happens (`ccache` ?). Anyway, solved if I remove the lines referencing the other Slicer in `SlicerSALTLauncherSettings.ini`. It works!

For completion, your requested files, 

`SlicerSALTLauncherSettings.ini`

```
[General]
launcherNoSplashScreen=false
launcherSplashImagePath=/home/user/Software/Shape/SALT/src/Applications/SlicerSALTApp/Resources/Images/SplashScreen.png
launcherSplashScreenHideDelayMs=3000
additionalLauncherHelpShortArgument=-h
additionalLauncherHelpLongArgument=--help
additionalLauncherNoSplashArguments=--no-splash,--help,--version,--home,--program-path,--no-main-window,--settings-path,--temporary-path





[Application]
path=<APPLAUNCHER_DIR>/bin/./SlicerSALTApp-real
arguments=
name=SlicerSALT
revision=04917a6
organizationDomain=kitware.com
organizationName=Kitware, Inc.

[ExtraApplicationToLaunch]

designer/shortArgument=
designer/help=Start Qt designer using Slicer plugins
designer/path=/usr/bin/designer
designer/arguments=

gnome-terminal/shortArgument=
gnome-terminal/help=Start gnome-terminal
gnome-terminal/path=/usr/bin/gnome-terminal
gnome-terminal/arguments=

ddd/shortArgument=
ddd/help=Start ddd
ddd/path=/usr/bin/ddd
ddd/arguments=

gdb/shortArgument=
gdb/help=Start gdb
gdb/path=/usr/bin/gdb
gdb/arguments=


[Environment]
additionalPathVariables=QT_PLUGIN_PATH,PYTHONPATH

[LibraryPaths]
1\path=<APPLAUNCHER_SETTINGS_DIR>/bin/.
2\path=../lib/SlicerSALT-4.9/qt-loadable-modules
3\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/cli-modules/.
4\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/qt-loadable-modules/.
5\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/VTKv9-build/lib/.
6\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/teem-build/bin/.
7\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/DCMTK-build/lib/.
8\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/ITKv4-build/lib/.
9\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/CTK-build/CTK-build/bin/.
10\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/CTK-build/PythonQt-build/.
11\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/LibArchive-install/lib
12\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/SlicerExecutionModel-build/ModuleDescriptionParser/bin/.
size=12

[Paths]
1\path=<APPLAUNCHER_SETTINGS_DIR>/bin/.
2\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/cli-modules/.
3\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/teem-build/bin/.
size=3

[EnvironmentVariables]
SLICER_HOME=/home/user/Software/Shape/SALT/buildRelWithDebInfo/Slicer-build
ITK_AUTOLOAD_PATH=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/ITKFactories/.
SSL_CERT_FILE=<APPLAUNCHER_SETTINGS_DIR>/share/SlicerSALT-4.9/Slicer.crt



[QT_PLUGIN_PATH]
1\path=<APPLAUNCHER_SETTINGS_DIR>/bin
2\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/CTK-build/CTK-build/bin
3\path=/usr/plugins
size=3

[PYTHONPATH]
1\path=<APPLAUNCHER_SETTINGS_DIR>/bin/.
2\path=<APPLAUNCHER_SETTINGS_DIR>/bin/Python
3\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/qt-loadable-modules/.
4\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/qt-loadable-modules/Python
5\path=<APPLAUNCHER_SETTINGS_DIR>/lib/SlicerSALT-4.9/qt-scripted-modules
6\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/Slicer-build/bin
7\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/Slicer-build/bin/Python
8\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/Slicer-build/lib/Slicer-4.9/qt-loadable-modules
9\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/Slicer-build/lib/Slicer-4.9/qt-loadable-modules/Python
10\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/Slicer-build/lib/Slicer-4.9/qt-scripted-modules
11\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/VTKv9-build/lib/python2.7/site-packages
12\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/CTK-build/CTK-build/bin/Python
13\path=/home/user/Software/Slicer/buildSystemQtPython-RelWithDebInfo/CTK-build/CTK-build/bin
14\path=/home/user/.virtualenvs/slicer/lib/python27.zip
15\path=/home/user/.virtualenvs/slicer/lib/python2.7
16\path=/home/user/.virtualenvs/slicer/lib/python2.7/plat-linux2
17\path=/home/user/.virtualenvs/slicer/lib/python2.7/lib-tk
18\path=/home/user/.virtualenvs/slicer/lib/python2.7/lib-old
19\path=/home/user/.virtualenvs/slicer/lib/python2.7/lib-dynload
20\path=/usr/lib64/python2.7
21\path=/usr/lib/python2.7
22\path=/usr/lib/python2.7/plat-linux2
23\path=/usr/lib64/python2.7/lib-tk
24\path=/usr/lib/python2.7/lib-tk
25\path=/home/user/.virtualenvs/slicer/lib/python2.7/site-packages
26\path=/home/user/Software/ITK/build-master/Wrapping/Generators/Python
27\path=/home/user/Software/ITK/build-master/lib
28\path=/home/user/.virtualenvs/slicer/lib/python2.7/site-packages
29\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/VTKv9-build/lib/python2.7/site-packages
30\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/CTK-build/CTK-build/bin/Python
31\path=/home/user/Software/Shape/SALT/buildRelWithDebInfo/CTK-build/CTK-build/bin/.
size=31

```

I am using system python, but VTK  still wraps python at build time, the `vtkCommonKitPython.so` is there:

```
/home/usr/Software/Shape/SALT/buildRelWithDebInfo/VTKv9-build/lib/libvtkCommonKitPython27D-9.0.so
/home/usr/Software/Shape/SALT/buildRelWithDebInfo/VTKv9-build/lib/libvtkCommonKitPython27D-9.0.so.1
/home/usr/Software/Shape/SALT/buildRelWithDebInfo/VTKv9-build/lib/python2.7/site-packages/vtkmodules/vtkCommonKitPython.so
```

**Comment by phcerdan** [comment]
Next steps:
- [ ] Enable `Sequences`
- [ ] Enable External Modules.

**Comment by jcfr** [comment]
@phcerdan Thanks for your help, this topic (and the one in your fork) have been updated

**Comment by phcerdan** [comment]
Thanks @jcfr, testing it, and hopefully, we can merge soon and start adding external projects.

**Comment by phcerdan** [comment]
It works but hitting:

```
-- Build files have been written to: /home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build/ShapeRegressionExtension-build
[13/16] Performing build step for 'ShapeRegressionExtension'
ninja: error: build.ninja:962: multiple rules generate lib/SlicerSALT-4.9/qt-scripted-modules/Resources/Icons/ShapeRegressionExtension.png [-w dupbuild=err]

FAILED: ShapeRegressionExtension-prefix/src/ShapeRegressionExtension-stamp/ShapeRegressionExtension-build
cd /home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build/ShapeRegressionExtension-build && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
FAILED: ShapeRegressionExtension-prefix/src/ShapeRegressionExtension-stamp/ShapeRegressionExtension-build
cd /home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /home/user/Software/Shape/SALT/buildRelWithDebInfo/ShapeRegressionExtension-prefix/src/ShapeRegressionExtension-stamp/ShapeRegressionExtension-build
ninja: build stopped: subcommand failed.

```

`ninja -w dupbuild=warn ShapePopulationViewer`

**Comment by jcfr** [comment]
So that we can move forward with the integration, would be great to get one positive review.

Packaging of all extensions work as expected.

There only few minor issues that should be addressed afterward:
* the logo on the left is huge. This is tracked by https://github.com/KitwareMedical/SlicerCustomAppTemplate/issues/6
* the loading of SequenceSampleData trigger an error. This is tracked by https://github.com/SlicerRt/Sequences/pull/50

**Pull request merged**
